include hyde.conf

# Add your custom configurations here
font_size 12.0
window_padding_width 15
confirm_os_window_close 0

map ctrl+c       copy_and_clear_or_interrupt
map ctrl+v       paste_from_clipboard
