# █░█ █▀ █▀▀ █▀█   █▀█ █▀█ █▀▀ █▀▀ █▀
# █▄█ ▄█ ██▄ █▀▄   █▀▀ █▀▄ ██▄ █▀░ ▄█

# Set your personal hyprland configuration here

# █▀▀ █▄░█ █░█
# ██▄ █░▀█ ▀▄▀

env = EDITOR,nvim 
env = SUDO_EDITOR,$EDITOR
env = BROWSER, zen-browser

# █░░ ▄▀█ █░█ █▄░█ █▀▀ █░█
# █▄▄ █▀█ █▄█ █░▀█ █▄▄ █▀█

exec-once = sleep 30 && bash ~/Dropbox/backup-daily-dropbox.sh
exec-once = sleep 60 && dropbox
exec-once = sleep 90 && bash ~/OneDrive/backup-daily-onedrive.sh
exec-once = sleep 120 && onedrive --monitor
# exec-shutdown = onedrive --sync 2>&1 > ~/log-onedrive.txt
exec-once = sleep 150 && npm run start --prefix ~/whatsapp-electron/ 2>&1| tee ~/log-whatsapp.txt

# █▄▀ █▀▀ █▄█ █▄▄ █ █▄░█ █▀▄ █ █▄░█ █▀▀ █▀
# █░█ ██▄ ░█░ █▄█ █ █░▀█ █▄▀ █ █░▀█ █▄█ ▄█

# Main modifier
$mainMod = Super # super / meta / windows key

# Assign apps
$term = kitty
$editor = kitty -e nvim
$file = kitty -e yazi
$browser = zen-browser

# Application shortcuts
bind = $mainMod, Return, exec, $term # launch terminal emulator
bind = $mainMod, E, exec, $file # launch file manager
bind = $mainMod, C, exec, $editor # launch text editor
bind = $mainMod, B, exec, $browser # launch web browser
# bind = Ctrl+Shift, Escape, exec, $scrPath/sysmonlaunch.sh # launch system monitor (htop/btop or fallback to top)

bind = Super+Shift, B, exec, nyxt 

# Move/Change window focus
bind = $mainMod, H, movefocus, l
bind = $mainMod, L, movefocus, r
bind = $mainMod, K, movefocus, u
bind = $mainMod, J, movefocus, d


# █ █▄░█ █▀█ █░█ ▀█▀
# █ █░▀█ █▀▀ █▄█ ░█░

input {
    # kb_layout = us
    # kb_variant = altgr-intl
    repeat_delay = 250
    repeat_rate = 50
    sensitivity = 1 # -1.0 - 1.0, 0 means no modification.
    force_no_accel = 0
}


# █░█░█ █ █▄░█ █▀▄ █▀█ █░█░█   █▀█ █░█ █░░ █▀▀ █▀
# ▀▄▀▄▀ █ █░▀█ █▄▀ █▄█ ▀▄▀▄▀   █▀▄ █▄█ █▄▄ ██▄ ▄█

# windowrulev2 = opacity 0.60 0.60,class:^(Steam)$
# windowrulev2 = opacity 0.60 0.60,class:^(steam)$
# windowrulev2 = opacity 0.60 0.60,class:^(steamwebhelper)$
# windowrulev2 = opacity 0.60 0.60,class:^(Spotify)$


# █░█ █▀▄▀█
# ▀▄▀ █░▀░█

# bind = Ctrl+Alt_L, V, submap, passthrough
# submap = passthrough
# bind = Ctrl+Alt_L, V, submap, reset
# submap = reset
