# █░█ █▀ █▀▀ █▀█   █▀█ █▀█ █▀▀ █▀▀ █▀
# █▄█ ▄█ ██▄ █▀▄   █▀▀ █▀▄ ██▄ █▀░ ▄█

# Set your personal hyprland configuration here

# █▀▀ █▄░█ █░█
# ██▄ █░▀█ ▀▄▀

env = EDITOR,nvim 
env = SUDO_EDITOR,$EDITOR
env = BROWSER, zen-browser

# Postgres
env = PGHOST,127.0.0.1
env = PGPORT,5432
env = PGDATABASE,postgres
env = PGUSER,postgres

# # AppImage
# env = QT_PLUGIN_PATH,/usr/lib/qt/plugins
# env = QT_QPA_PLATFORM,xcb

# █░░ ▄▀█ █░█ █▄░█ █▀▀ █░█
# █▄▄ █▀█ █▄█ █░▀█ █▄▄ █▀█

# Backup and sync Dropbox
exec-once = sleep 30 && bash ~/Dropbox/backup-daily-dropbox.sh
exec-once = sleep 60 && dropbox

# Backup and sync OneDrive
exec-once = sleep 90 && bash ~/OneDrive/backup-daily-onedrive.sh
exec-once = sleep 120 && onedrive --monitor

# █▀▄▀█ █▀█ █▄░█ █ ▀█▀ █▀█ █▀█ █▀
# █░▀░█ █▄█ █░▀█ █ ░█░ █▄█ █▀▄ ▄█

# Set your monitor configuration here
monitor=,highres@highrr,auto,1
monitor=HDMI-A-1,preferred,auto-left,1

# █▄▀ █▀▀ █▄█ █▄▄ █ █▄░█ █▀▄ █ █▄░█ █▀▀ █▀
# █░█ ██▄ ░█░ █▄█ █ █░▀█ █▄▀ █ █░▀█ █▄█ ▄█

# Main modifier
$mainMod = Super # super / meta / windows key

# Assign apps
$term = kitty
$editor = kitty -e nvim
$file = kitty -e yazi
$browser = zen-browser

# Application shortcuts
bind = $mainMod, Return, exec, $term # launch terminal emulator
bind = $mainMod, E, exec, $file # launch file manager
bind = $mainMod, C, exec, $editor # launch text editor
bind = $mainMod, B, exec, $browser # launch web browser

# Move/Change window focus
bind = $mainMod, H, movefocus, l
bind = $mainMod, L, movefocus, r
bind = $mainMod, K, movefocus, u
bind = $mainMod, J, movefocus, d

# Windows
bind = $mainMod, Q, killactive  # Kill active window
bind = $mainMod, F, fullscreen, 0  # Set active window to fullscreen
bind = $mainMod, M, fullscreen, 1  # Maximize Window
bind = $mainMod, T, togglefloating # Toggle active windows into floating mode
bindm = $mainMod, mouse:272, movewindow  # Move window with the mouse
bindm = $mainMod, mouse:273, resizewindow # Resize window with the mouse

# █ █▄░█ █▀█ █░█ ▀█▀
# █ █░▀█ █▀▀ █▄█ ░█░

input {
    # kb_layout = us
    # kb_variant = altgr-intl
    repeat_delay = 250
    repeat_rate = 50
    sensitivity = 1
    force_no_accel = 0
}

# █░█░█ █ █▄░█ █▀▄ █▀█ █░█░█   █▀█ █░█ █░░ █▀▀ █▀
# ▀▄▀▄▀ █ █░▀█ █▄▀ █▄█ ▀▄▀▄▀   █▀▄ █▄█ █▄▄ ██▄ ▄█

# windowrule = opacity 0.9 override 0.7,title:(.*)
# windowrulev2 = opacity 0.60 0.60,class:^(Spotify)$

# █░█ █▀▄▀█
# ▀▄▀ █░▀░█

# bind = Ctrl+Alt_L, V, submap, passthrough
# submap = passthrough
# bind = Ctrl+Alt_L, V, submap, reset
# submap = reset
