[opener]
play = [
	{ run = 'mpv "$@"', orphan = true, for = "unix" },
]
edit = [
	{ run = '$EDITOR "$@"', block = true, for = "unix" },
]
open = [
	{ run = 'xdg-open "$@"', desc = "Open" },
]
extract = [
	{ run = 'ya pub extract --list "$@"', desc = "Extract here", for = "unix" },
	{ run = 'ya pub extract --list %*',   desc = "Extract here", for = "windows" },
]

[[plugin.prepend_previewers]]
mime = "application/{*zip,tar,bzip2,7z*,rar,xz,zstd,java-archive}"
run  = "ouch"

[[plugin.prepend_fetchers]]
id   = "git"
name = "*"  # use `url` if you're using the nightly version of Yazi
run  = "git"

[[plugin.prepend_fetchers]]
id   = "git"
name = "*/"  # use `url` if you're using the nightly version of Yazi
run  = "git"
