# -----------------------------------------------------
# Environment Variables
# name: "Custom"
# -----------------------------------------------------

env = EDITOR,nvim 
env = SUDO_EDITOR,$EDITOR
env = BROWSER, zen-browser
