# ----------------------------------------------------- 
# Monitor Setup
# name: "1920x1200"
# ----------------------------------------------------- 

# monitor=eDP-1,1920x1080,0x0,1
# monitor=HDMI-A-1,1920x1080,-1920x0,1

# Set your monitor configuration here
monitor=,highres@highrr,auto,1
monitor=HDMI-A-1,preferred,auto-left,1
