# Include Custom Configuration
# Add the text "include ./custom.conf" in ~/.config/kitty/kitty.conf to overwrite the default configuration

# Add your custom configurations here
font_size                   12.0
window_padding_width        15
# background_opacity          0.7
# dynamic_background_opacity  yes
confirm_os_window_close     0

map ctrl+c       copy_and_clear_or_interrupt
map ctrl+v       paste_from_clipboard
